### ISSUE TITLE
A fix to an infinite loop bug and a modification to fit with save/load map function

### ISSUE THREAD

**Issue by cyizhuo** [fishmarch/ORB-SLAM3-Remove-Bad#1]
Thanks for this great code, I tested it through my orbslam3 env and it saved so much memory while building maps(took me a few days to fit the shared_ptr code though). 

It turns out that shared_ptr doesn't downsize the saved map file nor the memory usage while relocalizing with saved map, but still big help to build a large map.

And I have a fix to an infinite loop bug and a modification to fit with save/load map function I'd like to share.

## A fix to an infinite loop bug

So I have found an infinite loop bug in `KeyFrame::UpdateConnections()`, and I fixed it by chage the following code

```cpp
if (mit->second >= th) {
    vPairs.push_back(make_pair(mit->second, mit->first));
    (mit->first)->AddConnection(pThis, mit->second);
    mit++;
} else {
    mit = KFcounter.erase(mit);
}
```

to 

```cpp
if (mit->second >= th) {
    vPairs.push_back(make_pair(mit->second, mit->first));
    (mit->first)->AddConnection(pThis, mit->second);
}
```

just like the raw orbslam3 code.

## A modification to fit with save/load map function

As the raw orbslam3 code added the save/load map function, it actually needs to be modified to fit with this shared_ptr code, we need to chage the `System::SaveAtlas()` code. I did this modification to avoid compiling errors.

Find 2 section codes of

```cpp
oa << strVocabularyName;
oa << strVocabularyChecksum;
oa << mpAtlas;
```

and change them to

```cpp
oa << strVocabularyName;
oa << strVocabularyChecksum;
oa << mpAtlas;
oa << Map::nNextId;
oa << Frame::nNextId;
oa << KeyFrame::nNextId;
oa << MapPoint::nNextId;
oa << GeometricCamera::nNextId;
```

And 2 section codes in `System::LoadAtlas()` from

```cpp
ia >> strFileVoc;
ia >> strVocChecksum;
ia >> mpAtlas;
```

to 

```cpp
ia >> strFileVoc;
ia >> strVocChecksum;
ia >> mpAtlas;
ia >> Map::nNextId;
ia >> Frame::nNextId;
ia >> KeyFrame::nNextId;
ia >> MapPoint::nNextId;
ia >> GeometricCamera::nNextId;
```

And we also need to comment following lines of code in `Atlas::serialize()` 

```cpp
ar& Map::nNextId;
ar& Frame::nNextId;
ar& KeyFrame::nNextId;
ar& MapPoint::nNextId;
ar& GeometricCamera::nNextId;
```

**Comment by fishmarch** [comment]
Thanks for your contributions. I did not use original save/load map function before, thus I did not change these codes. This repo just release the memory of bad map points and keyframes, which will not be saved in a map. Thus the saved map size would not  be smaller. If you want to decrease map file size, you can consider to delete those useless descriptors, this would help a lot if you did not try before.

**Comment by fishmarch** [comment]
By the way, why  the codes for KeyFrame::UpdateConnections() will cause infinite loop? I changed these codes because the original ones may cause unidirectional connection, thus shared_ptr may not work as desired. See my another repo, https://github.com/fishmarch/ORB_SLAM3_Fixed

**Comment by cyizhuo** [comment]
> By the way, why the codes for KeyFrame::UpdateConnections() will cause infinite loop? I changed these codes because the original ones may cause unidirectional connection, thus shared_ptr may not work as desired. See my another repo, https://github.com/fishmarch/ORB_SLAM3_Fixed

Yes it caused infinite loop on my machine, but it could be my own mistake somehow since the shared_ptr changes a lot of codes. And after my own fix, it works fine and did saved running memory, so I'm gonna leave it that way and never touch it again......

**Comment by cyizhuo** [comment]
> Thanks for your contributions. I did not use original save/load map function before, thus I did not change these codes. This repo just release the memory of bad map points and keyframes, which will not be saved in a map. Thus the saved map size would not be smaller. If you want to decrease map file size, you can consider to delete those useless descriptors, this would help a lot if you did not try before.

Now there are useless descriptors needed to be deleted too? This orbslam3 is just to complex for me. Should I just use shared_ptr for descriptors too, or is there another way to delete useless descriptors?

**Comment by fishmarch** [comment]
> > Thanks for your contributions. I did not use original save/load map function before, thus I did not change these codes. This repo just release the memory of bad map points and keyframes, which will not be saved in a map. Thus the saved map size would not be smaller. If you want to decrease map file size, you can consider to delete those useless descriptors, this would help a lot if you did not try before.
> 
> Now there are useless descriptors needed to be deleted too? This orbslam3 is just to complex for me. Should I just use shared_ptr for descriptors too, or is there another way to delete useless descriptors?

I am not sure for the save/load function from of the original ORB3. If all of keypoints and descriptors are saved, they will contribute to lots of unnecessary size. Instead you can just save those for valid mappoints. You can refer to my another repo, here.

https://github.com/fishmarch/SLAM_Map_Compression/blob/24966a20e063eaabda46ac1dd22f6f47441814ca/src/Map.cc#L266-L283.

**Comment by cyizhuo** [comment]
Great! Your paper/code about map compression is actually the next step of my plan to modify orbslam3, thanks for the work and your reply!
