### ISSUE TITLE
Memory leaking problem  consulting

### ISSUE THREAD

**Issue by ouhuajing** [fishmarch/ORB-SLAM3-Remove-Bad#3]
Hello, I am very thank you for your contribution.
I also noted ORB-slam3 memory leaking is so serious. I noted you cleared some memory in SetBadFlag function. Is it can release all bad KeyFrame memory absolutly? Besides, Do you use share_ptr to manage memory for releasing aotumatically memory when last pointer is erased?

**Comment by fishmarch** [comment]
Yes, this project is using shared_ptr for Keyframes and MapPoints to release those memory automatically.
